### ISSUE TITLE
反序列化出现 MemberAccessException 异常

### ISSUE THREAD

**Issue by asyura** [Dogwei/Swifter.Json#25]
json字符串是其他工具生成的，用Swifter.Json反序列化出现这个异常，其中json字符串有的属性是只读，即只有set

**Comment by asyura** [comment]
以下是异常信息：

> System.MemberAccessException: This member 'Classes' no set method or cannot access.
   at FastObjectRW_NormalizedField_9d0c8a5b517e4850ba36b02c1074ebc0.OnWriteValue(Int64 , IValueReader )
   at Swifter.Json.JsonDeserializer`1.FastReadObject(IId64DataRW`1 dataWriter)
   at Swifter.Json.JsonDeserializer`1.ReadObject(IDataWriter`1 dataWriter)
   at Swifter.RW.FastObjectInterface`1.ReadValue(IValueReader valueReader)
   at Swifter.RW.OneRankArrayRW`2.OnWriteValue(Int32 key, IValueReader valueReader)
   at Swifter.Json.JsonDeserializer`1.NoInliningReadArray(IDataWriter`1 dataWriter)
   at Swifter.Json.JsonDeserializer`1.ReadArray(IDataWriter`1 dataWriter)
   at Swifter.RW.ArrayInterface`1.ReadValue(IValueReader valueReader)

**Comment by asyura** [comment]
json字符串是用newtonsoft json序列化的，用newtonsoft json反序列化也没问题

**Comment by Dogwei** [comment]
您可以在初始化处加上这句代码：
            FastObjectRW.DefaultOptions &= ~FastObjectRWOptions.CannotSetException;

**Comment by asyura** [comment]
谢谢
