### ISSUE TITLE
特性用法[RWFormat("yyyy-MM-dd")]报错'Swifter.RW.StaticFastObjectRW`1' threw an exception.

### ISSUE THREAD

**Issue by wilikeit** [Dogwei/Swifter.Json#67]
sdk：dotnet 6.0
Swifter.Json版本：1.6.0.7
系统：windows10

```go
using Swifter.Json;
using Swifter.RW;

[RWObject(SkipDefaultValue = RWBoolean.Yes)]
public class Demo
{
    public int Id;
    public string Name;
    [RWField("Age")]
    private int age;
    [RWField(SkipDefaultValue = RWBoolean.No)]
    public int? Sex;
    [RWFormat("yyyy-MM-dd")]  //添加这个就报错
    public DateTime Birthday { get; set; }

    public static void Main()
    {
        var obj = new Demo { Name = "Dogwei", age = 24, Birthday = DateTime.Parse("1996-01-08") };
        var json = JsonFormatter.SerializeObject(obj);
        var dest = JsonFormatter.DeserializeObject<Demo>(json);

        Console.WriteLine(json);
        // {"Age":24,"Birthday":"1996-01-08","Name":"Dogwei","Sex":null}
    }
}

```

报错：
Unhandled exception. System.TypeInitializationException: The type initializer for 'Swifter.RW.StaticFastObjectRW`1' threw an exception.
 ---> System.NotSupportedException: Specified method is not supported.
   at Swifter.RW.RWFormatAttribute.set_InterfaceType(Type value)
   at Swifter.RW.RWFieldAttribute..ctor()
   at Swifter.RW.RWFormatAttribute..ctor(String format)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Swifter.RW.StaticFastObjectRW`1.GetFields(Type type, OpenDictionary`2 dicFields, RWObjectAttribute[] objectAttributes)
   at Swifter.RW.StaticFastObjectRW`1..cctor()
   --- End of inner exception stack trace ---
   at Swifter.RW.FastObjectInterface`1.WriteValue(IValueWriter valueWriter, T value)
   at Demo.Main() in D:\C#\code\ConsoleApp1-dotnet6\Program.cs:line 19

D:\C#\code\ConsoleApp1-dotnet6\bin\Debug\net6.0\ConsoleApp1-dotnet6.exe (进程 26036)已退出，代码为 -532462766。
按任意键关闭此窗口. . .

直接 从官网复制的例子，能帮忙看下是什么原因吗？

**Comment by Dogwei** [comment]
这是迭代过程中疏忽导致的 BUG。
现在已经修复，晚点发一个版本。

如图所示，我在这个属性里抛出了异常，但我疏忽了这个函数在父级构造函数里一定会被调用。
![image](https://github.com/Dogwei/Swifter.Json/assets/14845492/0f8db989-2657-4e13-839f-fd2677d09eea)

**Comment by wilikeit** [comment]
好 的，用了 1.6.0.6也不行，麻烦大佬修复 下。

**Comment by Dogwei** [comment]
老铁，1.6.0.8 已经修复该问题。
